worker_processes  1;

error_log  /opt/nginx/logs/error.log info;
pid        /opt/nginx/logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    server {
        listen              443 ssl;
        server_name         localhost;

        ssl_certificate     /opt/nginx/nginx-conf/server.crt;
        ssl_certificate_key /opt/nginx/nginx-conf/server.key;
        ssl_protocols       TLSv1.3;

        # STUDENT TASK: migrate this from classical to hybrid PQC.
        ssl_ecdh_curve      X25519;

        location / {
            default_type text/plain;
            return 200 "Reto 2 NGINX TLS endpoint
";
        }
    }
}
